Creación objetos Game y GameService, Metodo InitializeRoutes y el endpoint "/games"
repositoryGamesUNAL/repositorioJuegos pull request #4
Opened 2024-12-03 06:31 UTC by Hzuletam

para la funcionalidad Crearjuego, hice el objeto Game que recibe en el contructor los siguientes parametros:
Game({
  name:string, 
  date:string, 
  purpose:string, 
  thematic:object, 
  genre:string, 
  materials:object, 
  objectives:string, 
  time:string})
también se creó un objeto GameService(services/gameService.ts), el cual solo puede tener una instancia por medio del getInstance() , este almacena los juegos en un array con objetos "Game" , luego se creó el endpoint "/games" y el método InitializeRoutes(Routes/index.ts) para ser invocado desde app.ts e inicializar todos nuestros endpoints, todavía hace falta hacer los throws dentro de los metodos de GameService para devolver adecuadamente los request desde el endpoint con su debido status code de error

2024-12-03 06:31 UTC, Hzuletam commented
tremenda cagada

2024-12-03 13:34 UTC, juanseb253 requested changes

2024-12-03 13:34 UTC, juanseb253 commented on games-repository-api/src/routes/gamesRouter.ts
usar arrow functions

2024-12-03 13:34 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    getGame(id:number): object{
cambiar nombre por findGameById

2024-12-03 13:34 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    getGames(): object{
cambiar nombre por findAllGames

2024-12-03 13:34 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    postGame(data:{name:string,
cambiar nombre por createGame, ademas si se va a pasar un parametro tan gigante, se deberia crear un modelo o una clase utilitaria

2024-12-03 13:34 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +        for(let instance  of this._storage){
Desestructurar instance en cada uno de sus elementos antes de darles ds valores

2024-12-03 13:34 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +        //defines the game object types
Porque se define otra vez el juego?, deberia usarse el modelo creado

2024-12-03 13:34 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +            //take out the data
Lo mismo, no definir un tipo directamente

2024-12-03 13:41 UTC, juanseb253 requested changes

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/routes/gamesRouter.ts
> +gamesRouter.get("/:id", function (req:Request , res:Response, next:any): any {
cambiar a arrow function

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/routes/gamesRouter.ts
> +gamesRouter.get("/",function (req:Request , res:Response , next:any): any {
cambiar a arrow function

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/routes/gamesRouter.ts
> +const service:GameService | null = GameService?.getInstance();
evitar definir tipos en el propio codigo

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/routes/gamesRouter.ts
> +gamesRouter.post("/",function (req:Request , res:Response, next:any): any {
arrow

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/routes/gamesRouter.ts
> +gamesRouter.patch("/:id", function (req:Request , res:Response, next:any): any {
arrow

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    private static _instance: null | GameService = null;
evitar definir tipos en caliente

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    static getInstance(): GameService | null {
ojo con definir tipos en caliente

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +            const newGame:Game = new Game({
evitar dependencias, si game.date tiene la misma info que data.date ¿porque se usan unos y otros?, tratar de unificar para legibilidad

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +        const res:{status:number, data:object} =
evitar definir tipos en caliente

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +                time:string}= {
si se van a usar varios campos de data, desestructurar previo a asignaciones

2024-12-03 13:41 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    editGame( id:number, changes:{name:string, description:string, fecha:string}): object
evitar definir tipos en caliente, y estamos seguros que deberia devolver un object?

2024-12-04 14:12 UTC, juanseb253 requested changes

2024-12-04 14:12 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    findAllGames(): object {
No deberia devolver un object, sino una lista de juegos

2024-12-04 14:12 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +        for (let instance of this._storage) {
recuerda desestructurar el objeto instancia

2024-12-04 14:12 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    findGameById(id: number): object {
no devolver object

2024-12-04 14:12 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    createGame(data: newGame): object {
no devolver object

2024-12-04 14:12 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +            const newGame: Game = new Game({
desestructurar data

2024-12-04 14:12 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    editGame(id: number, changes: changesOfGame): object {
no devolver object

2024-12-04 14:30 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +        const res: { status: number, data: object } = {
no usar object

2024-12-04 14:32 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    createGame(data: newGame): object {
tampoco aceptar object

2024-12-04 14:32 UTC, juanseb253 commented on games-repository-api/src/services/gameService.ts
> +    findGameById(id: number): object {
ni aceptar object como parametro

2024-12-06 07:22 UTC, juanseb253 approved these changes

2024-12-06 07:23 UTC, merged